[package]
name = "fusee-cli"
version = "0.1.0"
authors = ["Justus K <justus.k@protonmail.com>"]
edition = "2018"

[dependencies]
confy = "0.4.0"
thiserror = "1.0.18"
termcolor = "1.1.0"
structopt = "0.3.14"

[dependencies.fusee]
path = "../"
